config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: [:show]
  resources :items do
    collection do
      get 'search'
      get 'import_page'
      post 'import'
    end
  end

  get 'data_exports/export_csv'
  get 'data_exports/user_export_csv'
  root to: "items#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items

  #バリデーション
  validates :name, presence: true
  validates :affiliation, presence: true
  validates :admin, inclusion: [true, false]
  #半角6~12文字で英大文字・英小文字・数字それぞれ１文字以上含む
  validates :password,on: :create ,format: { with:/\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[\d])\w{6,12}\z/, message: "Password is invalid. Include both letters and numbers"}
  #半角英数字のみ
  validates :employee_number, presence: true,uniqueness: true, format: { with:/\A[a-z0-9]+\z/i }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_admin
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.order("employee_number ASC")
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  
  end

  def destroy
    # @item.destroy
    # redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :employee_number, :affiliation, :admin)
  end

  def check_admin
    unless current_user&.admin?
      redirect_to root_path
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<%= render "shared/second-header" %>

<%= form_with model: @user,url: user_path(@user.id),id:'admin-edit-form' ,class: 'registration-main', local: true do |f| %>

  <%= render 'shared/error_messages', model: f.object %>

  <div class="admin-form-update">
    <h2 class='edit-user-title'>ユーザ情報変更画面（<%= @user.name%>）</h2>

    <div class="field">
      <%= f.label :email %><span class="indispensable">必須</span><br />
      <%= f.email_field :email,id:"admin-edit-email",class:"input-default", autofocus: true, autocomplete: "email" %>
      <span id="admin-edit-email-error" class="error-message"></span>
    </div>

    <div class="field">
      <%= f.label :社員番号 %><span class="indispensable">必須</span><br />
      <%= f.text_field :employee_number,id:"admin-edit-employee-number", class:"input-default", placeholder:"例) 1234", maxlength:"20" %>
      <span id="admin-edit-employee-number-error" class="error-message"></span>
    </div>

    <div class="field">
      <%= f.label :名前 %><span class="indispensable">必須</span><br />
      <%= f.text_area :name, id:"admin-edit-name", class:"input-text", placeholder:"例) 山田 太郎", maxlength:"40" %>
      <span id="admin-edit-name-error" class="error-message"></span>
    </div>
    <div class="field">
      <%= f.label :所属 %><span class="indispensable">必須</span><br />
      <%= f.text_area :affiliation, id:"admin-edit-affiliation", class:"input-text", placeholder:"例) 福岡支社", maxlength:"40"  %>
      <span id="admin-edit-affiliation-error" class="error-message"></span>
    </div>

    <div class="field">
      <%= f.label :管理者ユーザ %><br />
      <%= f.check_box :admin, class:"input-check-box" %>
    </div>

    <div>
      <div class='register-btn'>
        <%= f.submit "更新",id: "admin-submit-button", class:"register-red-btn"%>
      </div>

      <div class="input-btn-contents">
        <%=link_to 'もどる', users_path, class:"back-btn" %>
      </div>
    </div>

</div>

<% end %>

app/views/users/index.html.erb
<%= render "shared/second-header" %>

<div class="admin-user-contents">
  <div class='admin-user-contents-top'>
    ユーザ一覧
  </div>
  <%= link_to "csv出力", data_exports_user_export_csv_path(format: :csv) ,class:'list-hover btn-style'%>
  
  <table>
    <thead>
      <tr>
        <th>操作</th>    
        <th>社員番号</th>
        <th>名前</th>
        <th>Email</th>
        <th>所属</th>
        <th>管理者</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to "編集する", edit_user_path(user.id) %>
              <%= link_to "削除する", user_path(user.id), method: :delete %></td>
          <td><%= user.employee_number %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.affiliation %></td>
          <td><%= user.admin %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="input-btn-contents">
  <%=link_to 'もどる', root_path, class:"back-btn" %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>