config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: [:show]
  resources :items do
    collection do
      get 'search'
      get 'import_page'
      post 'import'
    end
  end

  get 'data_exports/export_csv'
  get 'data_exports/user_export_csv'
  root to: "items#index"
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to("/")  do %>
      <%= image_tag("ネット接続アイコン3.png", class:"idm-icon") %>
      <div class="app-title">IDMアプリ</div>
    <% end %>
    <div class='title-content'>
      <div class='title-message'>
        データ保存・通信をする情報機器を管理するアプリ
      </div>

      <%= search_form_for Item.ransack(params[:q]), url: search_items_path, local: true, html:{class: "search-form"} do |f| %>
        <%= f.text_field :item_or_serial_number_or_user_name_cont, placeholder: '機器名・S/N・所有者名検索（部分一致）', class: "input-box" %>
        <%= f.number_field :id_eq, placeholder: '機器id検索（完全一致）', class: "input-box" %>
        <%= f.submit "検索", class: "search-button list-hover" %>
    </div>
  </div>

  <div class='nav'>
    <div class='lists-left'>
      <div class='category-list' id='category'>
        <div class='category-lists list-hover btn-style' id='category-search-btn'>
          カテゴリー検索
        </div>
        <div class='hidden' id='category-pull-down'>
          <%= f.collection_check_boxes :category_id_in, Category.all, :id, :name do |cb| %>
            <div class="form-check">
              <%= cb.check_box %>
              <%= cb.label %>
            </div>
          <% end %>
        </div>
      </div>
        
      <div class='status-list' id='status'>
        <div class='status-lists list-hover btn-style' id='status-search-btn'>
          利用状況検索
        </div>
        <div class='hidden' id='status-pull-down'>
          <%= f.collection_check_boxes :status_id_in, Status.all, :id, :name do |cb| %>
            <div class="form-check">
              <%= cb.check_box %>
              <%= cb.label %>
            </div>
          <% end %>
      <% end %><%#=search_form_forの終了場所%>
        </div>
      </div>
    </div>



    <ul class='lists-right'>
      <% if user_signed_in? %>
        <% if current_user&.admin?%>
        <li><%= link_to "ユーザ一覧", users_path, class: "user-list list-hover btn-style" %></li> 
        <% end %>
        <li><%= link_to current_user.name, edit_user_registration_path, class: "user-name list-hover btn-style" %></li> 
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout list-hover btn-style" %></li> 
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login list-hover btn-style" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up list-hover btn-style" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_index-list-header.html.erb
<thead>
  <tr>
    <th>機器id</th>
    <th>状況</th>
    <th>機器種類</th>
    <th>機器名</th>
    <th>所属</th>
    <th>所有者名</th>
    <th>購入年月</th>
    <th>利用予定年数</th>
  </tr>
</thead>

app/views/shared/_index-list.html.erb
  <tbody>
    <tr>
      <td>
          <%= link_to item_path(item.id) do %>
          <div class='item-id list-hover'>
            <%= item.id %>
          </div>
          <% end %>
        </div>
      </td>
      <td>
        <div class='item-status'>
          <%= item.status.name %>
        </div>
      </td>
      <td>
        <div class='item-category'>
          <%= item.category.name %>
        </div>
      </td>
      <td>
        <div class='item-name'>
          <%= item.item %>
        </div>
      </td>
      <td>
        <div class='item-user-affiliation'>
          <%= item.user.affiliation %>
        </div>
      </td>
      <td>
        <div class='item-user-name'>
          <%= item.user.name %>
        </div>
      </td>
      <td>
        <div class='item-purchase-date'>
          <%= item.purchase_date %>
        </div>
      </td>
      <td>
        <div class='item-years-of-use'>
          <%= item.years_of_use %>
        </div>
      </td>
    </tr>
  </tbody>

app/views/shared/_new-input-form.html.erb
<%= form_with model:@item, id: 'item-form', local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
  <div class="new-items">
    <div class="weight-bold-text">【入力項目】</div>

    <div class="items-input-contents">
      <div class="weight-bold-text">
        社員番号
        <span class="indispensable">必須</span>
      </div>
      <% if @item.new_record? %><%#新規登録の時はカレントユーザの社員番号を初期値として設定%>
        <%= f.text_field :employee_number, value: current_user.employee_number , class:"items-text", id:"employee-number", placeholder:"例) 1234", maxlength:"20"  %>
      <% else %> <%#編集の時は登録されているユーザの社員番号を初期値として設定%>
        <%= f.text_field :employee_number, value: @employee_number , class:"items-text", id:"employee-number", placeholder:"例) 1234", maxlength:"20"  %>
      <% end %>
      <span id="employee-number-error" class="error-message"></span>
    </div>


    <div class="items-input-contents">
      <div class="weight-bold-text">
        状態
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
    </div>

    <div class="items-input-contents">
      <div class="weight-bold-text">
        機器種類
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
    </div>

    <div class="items-input-contents">
      <div class="weight-bold-text">
        機器名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :item, class:"items-text", id:"item-name", placeholder:"商品名（必須 30文字まで)", maxlength:"30" %>
      <span id="item-error" class="error-message"></span>
    </div>


    <div class="items-input-contents">
      <div class="weight-bold-text">
        メーカー
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :manufacturer, class:"items-text", id:"item-manufacturer", placeholder:"DELL,HPなど" ,maxlength:"30" %>
      <span id="manufacturer-error" class="error-message"></span>
    </div>
    <div class="items-input-contents">
      <div class="weight-bold-text">
        IPアドレス
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :ip, class:"items-text", id:"item-ip", placeholder:"DHCP or xxx.xxx.xxx.xxx"%>
      <span id="ip-error" class="error-message"></span>
    </div>

    <div class="items-input-contents">
      <div class="weight-bold-text">
        S/N
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :serial_number, class:"items-text", id:"item-serial-number", placeholder:"英数字のみ" ,maxlength:"20" %>
      <span id="serial-number-error" class="error-message"></span>
    </div>

    <div class="items-input-contents">
      <div class="weight-bold-text">
        購入年月
        <span class="indispensable">必須</span>
      </div>
      <%= f.date_field :purchase_date, class:"items-date", id:"item-purchase-date" %>
      <span id="purchase-date-error" class="error-message"></span>
    </div>

    <div class="items-input-contents">
      <div class="weight-bold-text">
        利用予定年数
        <span class="indispensable">必須</span>
      </div>
      <%= f.number_field :years_of_use, class:"items-number", id:"item-years-of-use" ,maxlength:"2" %><span>年</span>
      <span id="years-of-use-error" class="error-message"></span>
    </div>

    <div class="items-input-contents">
      <div class="weight-bold-text">
        備考
        <span class="Arbitrary">任意</span>
      </div>
      <%= f.text_area :remarks, class:"items-text-area", id:"item-remarks", placeholder:"備考（200文字まで)", maxlength:"200" %>
    </div>

    <div class="items-input-contents">
      <div class="weight-bold-text">
        ファイル添付
        <span class="Arbitrary">任意</span>
      </div>
      <div class="click-upload">
        <%= f.file_field :image, id:"item-file" %>
      </div>
    </div>

    <%# 下部ボタン %>
    <div class="input-btn-contents">
      <%= f.submit "登録する" ,id: 'submit-button', disabled: true, class:"input-btn" %><br>
    </div>
    <%# /下部ボタン %>
    <% end %>
</div>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to("/")  do %>
    <%= image_tag("ネット接続アイコン3.png", class:"idm-icon") %>
    <div class="app-title">IDMアプリ</div>
  <% end %>
</header>