config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: [:show]
  resources :items do
    collection do
      get 'search'
      get 'import_page'
      post 'import'
    end
  end

  get 'data_exports/export_csv'
  get 'data_exports/user_export_csv'
  root to: "items#index"
end

app/models/item.rb
#この記述でResolv::IPv4::Regexを使用することができる
require 'resolv'

class Item < ApplicationRecord
  #アソシエーション
  belongs_to :user

  #Active Strageのアソシエーション
  has_one_attached :image

  #ActiveHashのアソシエーション
  extend ActiveHash::Associations::ActiveRecordExtensions 
  belongs_to :category
  belongs_to :status

  #バリデーションを記述
  validates :status_id, presence: true 
  validates :item, presence: true
  validates :category_id, presence: true
  validates :manufacturer, presence: true
  #S/N英数字のみ
  validates :serial_number, presence: true,uniqueness: true, format: { with: /\A[A-Za-z0-9]+\z/ }
  #192.168.000.000形式もしくはDHCP
  validates :ip, presence: true, format: { with: /\A(?:DHCP|\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\z/ }
  #yyyy-mm-dd形式
  validates :purchase_date, presence: true
  #y年表示
  validates :years_of_use, presence: true


  #csv_import
  def self.import(file)
    all_count = 0
    failure_id = []
    failure_count = 0
    registration_count = 0
    alert = []
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      item = find_by(id: row["id"]) || new
      # 社員番号からuser.idを割り出す
      item.user = User.find_by(employee_number: row["社員番号"])
      # CSVからデータを取得し、設定する
      item.attributes = updatable_attributes(row)
      all_count += 1
      # 保存する
      if item.save
        registration_count += 1
      else
        failure_count += 1
        failure_id << row["id"]
      end
    end

    if failure_count == 0
      alert << "取り込み実施件数：#{all_count}件中、全件取り込み成功!"
      return alert
      #redirect_to items_import_page_path
    else
      alert << "取り込み実施件数：#{all_count}件中、取り込み失敗件数：#{failure_count}"
      failure_id.each do |id|
        alert << "取り込みエラー 対象id:#{id}"
      end 

      return alert
    end

  end

  def self.updatable_attributes(row)
    {id: row["id"], status_id: row["状態"], item: row["機器名"], category_id: row["機器種類"], manufacturer: row["メーカー名"], serial_number: row["S/N"], ip: row["IPアドレス"], purchase_date: row["購入年月"], years_of_use: row["利用予定年数"], remarks: row["備考"]}
  end


end

app/controllers/items_controller.rb
require 'csv'

class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index,:search ]
  before_action :set_item, only: [:edit, :show, :update]
  before_action :check_admin, only: [:import, :import_page]

  def index 
    @items = Item.order(id: "DESC")
  end

  def new
    @item = Item.new
  end

  def show
  end
  
  def create 
    employee_number = params[:item][:employee_number]
    user = User.find_by(employee_number: employee_number)
    @item = Item.new(item_params)
    @item.user = user
    if  @item.save
      redirect_to root_path
    else
      render :new
    end
  end


  
  def edit
    @employee_number = @item.user.employee_number
    unless @item.user_id == current_user.id || current_user&.admin?
      redirect_to root_path
    end
  end

  def update
    employee_number = params[:item][:employee_number]
    user = User.find_by(employee_number: employee_number)
    @item.user = user
    if @item.update(item_params)
      redirect_to item_path(@item.id)
    else
      render :edit
    end
  end


  def search
    @q = Item.ransack(params[:q])
    @items = @q.result
  end

  #csv取り込み
  def import
    # fileはtmpに自動で一時保存される
    flash[:alert] = Item.import(params[:file])
    redirect_to import_page_items_path
  end

  def import_page
  end

  private

  def item_params
    params.require(:item).permit(:image, :category_id, :item, :status_id, :manufacturer, :serial_number, :ip, :purchase_date, :years_of_use,:remarks)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def check_admin
    unless current_user&.admin?
      redirect_to root_path
    end
  end

  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%= render "shared/second-header" %>

<div class="items-register-form">
  <h2 class="items-title">機器情報を編集</h2>
    <%= render 'shared/new-input-form' %>

  <div class="input-btn-contents">
    <%=link_to 'もどる', item_path(@item.id), class:"back-btn" %>
  </div>

</div>

app/views/items/import_page.html.erb
<%= render "shared/second-header" %>

<div class = "csv-import">
  <div class="title-csv-import">情報機器 csv-import</div>
  <p>ファイルには以下の項目が必要です<br>
      id,状態,機器種類,機器名,メーカー名,社員番号,S/N,IPアドレス,購入年月,利用予定年数,備考<br>
  </p>

  <div>
    <% if flash[:alert].present? %>
      <% flash[:alert].each do |message| %>
        <div class="alert alert-danger">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  
  <div>
  <%= form_tag import_items_path, multipart: true do %>
    <%= file_field_tag :file ,id: 'csv-file-input', class:'list-hover btn-style' %>
    <%= submit_tag "インポート", class:'list-hover btn-style' %>
  <% end %>
  </div>

  <div class = "preview-form">
    <div id="csv-preview"></div>
  </div>

  <div>
    <p>【注意】<br>
      状態、機器種類については対象の番号で記述ください<br>
      入力条件に合わない場合は取込みに失敗してエラーを吐きます<br>
      csv出力ファイルは項目を網羅しており、取込みフォーマットとしてご利用頂けます
    </p>
  </div>

</div>

app/views/items/index.html.erb
<%= render "shared/header" %>

<div class='item-contents'>
  <div class='item-contents-top'>
    <div class='title-index'>
      ユーザ管理機器一覧
    </div>
    <div class="item-new-register">
      <% if user_signed_in? %>
        <%= link_to "csv出力", data_exports_export_csv_path(format: :csv) ,class:'list-hover btn-style'%>
        <% if  current_user&.admin?%>
          <%= link_to "csv入力", import_page_items_path ,class:'list-hover btn-style'%>
        <% end %>
      <% end %>
      <%=link_to '新規機器登録', new_item_path,class:'list-hover btn-style' %>
    </div>
  </div>

  <div class='item-list-supplement'>※機器idをクリックすると機器の詳細画面へ飛びます。<br>
  ※表示順序は購入年月が古い順に上から表示されます。</div>

  <table>
    <%= render "shared/index-list-header" %>
    <% @items.each do |item| %>
      <% if  current_user&.admin?%>
        <%= render partial: "shared/index-list", locals:{item: item } %>
      <% else %>
        <% if user_signed_in? && current_user.id == item.user_id %>
          <%= render partial: "shared/index-list", locals:{item: item } %>
        <% end %>
      <% end %>
    <% end %>
  </table>
</div>

app/views/items/new.html.erb
<%= render "shared/second-header" %>

<div class="items-register-form">
  <h2 class="items-title">機器情報を入力</h2>
    <%= render 'shared/new-input-form' %>

    <div class="input-btn-contents">
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>

</div>

app/views/items/search.html.erb
<%= render "shared/header" %>

<div class='item-contents'>
  <div class='item-contents-top'>
    <div class='title-index'>
      ユーザ管理機器一覧（検索結果）
    </div>
    <div class="item-new-register">
      <%=link_to '新規機器登録', new_item_path,class:'list-hover btn-style' %>
    </div>
  </div>
  <div class='item-list-supplement'>※機器idをクリックすると機器の詳細画面へ飛びます。<br>
  ※表示順序は購入年月が古い順に上から表示されます。</div>

  <table>
    <%= render "shared/index-list-header" %>
    <% @items.each do |item| %>
      <% if  current_user&.admin?%>
        <%= render partial: "shared/index-list", locals:{item: item } %>
      <% else %>
        <% if user_signed_in? && current_user.id == item.user_id %>
          <%= render partial: "shared/index-list", locals:{item: item } %>
        <% end %>
      <% end %>
    <% end %>
  </table>
</div>

app/views/items/show.html.erb
<%= render "shared/header" %>

<div class="item-show">
  <div class="item-box">
    <h2 class="items-title">機器情報詳細</h2>  

    <table>
      <tr>
        <th>機器ID</th>
        <td><%= @item.id %></td>
      </tr>
      <tr>
        <th>状態</th>
        <td><%= @item.status.name %></td>
      </tr>
      <tr>
        <th>所属</th>
        <td><%= @item.user.affiliation %></td>
      </tr>
      <tr>
        <th>所有者名</th>
        <td><%= @item.user.name %></td>
      </tr>
      <tr>
        <th>機器種類</th>
        <td><%= @item.category.name %></td>
      </tr>
      <tr>
        <th>機器名</th>
        <td><%= @item.item %></td>
      </tr>
      <tr>
        <th>メーカー</th>
        <td><%= @item.manufacturer %></td>
      </tr>
      <tr>
        <th>IPアドレス</th>
        <td><%= @item.ip %></td>
      </tr>
      <tr>
        <th>S/N</th>
        <td><%= @item.serial_number %></td>
      </tr>
      <tr>
        <th>購入年月</th>
        <td><%= @item.purchase_date %></td>
      </tr>
      <tr>
        <th>利用予定年数</th>
        <td><%= @item.years_of_use %></td>
      </tr>
      <tr>
        <th>備考</th>
        <td><%= @item.remarks %></td>
      </tr>
      <tr>
        <th>添付ファイル</th>
        <td>      
          <% if @item.image.attached? %>
            <%= link_to @item.image.filename, url_for(@item.image) %>
          <% else %>
            ファイルが存在しません
          <% end %>
        </td>
    </table>
    
    <div class='item-show-supplement'>※設置場所についてはユーザの所属をご変更ください</div>

    <% if user_signed_in? && current_user.id == @item.user_id || current_user&.admin?%>
      <%= link_to "機器情報の編集", edit_item_path(@item.id), method: :get, class: "item-red-btn" %>
      <%= link_to "削除", item_path(@item.id), method: :delete, class:"item-destroy" %>
    <% end %>

  </div>
  <%=link_to 'もどる', root_path, class:"back-btn" %>
</div>